universe = Docker
docker_image = jysgro/bowtie2:sam115_bcf118
requirements = (Target.HasCHTCStaging==TRUE)
transfer_input_files = bowtie.sh, 
file:///staging/groups/pepperell_group/Mtb_RNAseq/MtbNCBIH37Rv.fa, 
file:///staging/groups/pepperell_group/Mtb_RNAseq/fastq_out.tar.gz
transfer_output_files = bowtie_out.tar.gz
transfer_output_remaps = "bowtie_out.tar.gz = file:///staging/groups/pepperell_group/
Mtb_RNAseq/bowtie_out.tar.gz"
executable = bowtie.sh
log = $(batch_name)_$(jobName)_$(Process).log
error = $(batch_name)_$(jobName)_$(Process).err
output = $(batch_name)_$(jobName)_$(Process).out

should_transfer_files= YES
when_to_transfer_output = ON_EXIT
request_memory = 5GB
request_disk = 60GB
request_cpus = 1
jobName = bowtie
batch_name = m5GB_d60GB_1cpu

queue