universe = Docker
docker_image = ubuntu/python:3.10-22.04
requirements = (Target.HasCHTCStaging==TRUE)
transfer_input_files = gtftools.sh, file:///staging/groups/pepperell_group/Mtb_RNAseq/MtbNCBIH37Rv_ncRNAs_sORFs.gtf 
# transfer_output_files = gene_length.txt
# transfer_output_remaps = "qualimap_out.tar.gz = file:///staging/groups/pepperell_group/Mtb_RNAseq/qualimap_out.tar.gz"
executable = gtftools.sh
log = $(batch_name)_$(jobName)_$(Process).log
error = $(batch_name)_$(jobName)_$(Process).err
output = $(batch_name)_$(jobName)_$(Process).out

should_transfer_files= YES
when_to_transfer_output = ON_EXIT
request_memory = 5GB
request_disk = 5GB
request_cpus = 1
jobName = gtftools 
batch_name = m5GB_d5GB_1cpu

queue